<?php namespace JF;
/**

Copyright 2023 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-717030
Date:    2023-03-17 05:36:54
Version: v2023.2.15
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

date_default_timezone_set( 'America/New_York' );

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-717030",
    "email": {
        "subject": "New story submission",
        "template": "",
        "to": "mystory@bauermedia.co.uk",
        "cc": "",
        "bcc": "",
        "sendmail_from": ""
    },
    "admin": {
        "users": "admin:d028823684",
        "dataDelivery": "emailAndFile",
        "save2dbExample": false
    },
    "thankyou": {
        "url": "https:\/\/www.thestorypeople.co.uk\/thank-you",
        "message": "Your story has been sent. Thank You!",
        "seconds": "10"
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "yellow"
        },
        "Select2": {
            "enabled": false
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Complete our 5-minute form to find out how much your story is worth.",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f13",
            "cid": "c72"
        },
        {
            "label": "First name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "firstname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Surname",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "lastname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c31",
            "id": "f5"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Date of birth",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "daysOfWeekDisabled": {
                        "d0": false,
                        "d5": false
                    },
                    "startDate": "",
                    "endDate": "",
                    "format": "dd\/mm\/yyyy",
                    "startView": "2",
                    "minViewMode": "0"
                }
            },
            "id": "f6",
            "cid": "c39"
        },
        {
            "label": "Address",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "fa fa-map-marker"
                }
            },
            "id": "f9",
            "cid": "c47"
        },
        {
            "label": "Postcode",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-map-marker"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f10",
            "cid": "c52"
        },
        {
            "label": "Phone number",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": true,
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9 -+.]+",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    },
                    "phonenumber": {
                        "enabled": false
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f11",
            "cid": "c57"
        },
        {
            "label": "Please give us a brief description of your story (no more than 350 words). We will contact you for more details.",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "fa fa-file-text"
                }
            },
            "id": "f15",
            "cid": "c83",
            "labelHide": false
        },
        {
            "label": "Photos",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "maxFileCount": "3",
                    "browseLabel": "Choose file\/s",
                    "allowedFileExtensions": "png,jpg,jpeg,gif"
                },
                "multiple": true,
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "VALUE MY STORY",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "autoResponse": {
        "subject": "",
        "template": "",
        "replyTo": ""
    },
    "licenseKey": "",
    "copyFrom": "jqueryform-ae18a8",
    "seo": {
        "trackerId": "UA-11859750-48",
        "title": "The Story People form"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class